# Generated by Django 5.1.4 on 2024-12-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_use', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
